### ISSUE TITLE
The link to the 'Find my bus area' and 'Find my rail zone' services need to open in a new tab.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-find-a-ticket#101]
The link to the 'Find my bus area' and 'Find my rail zone' services need to open in a new tab, as users will want to refer back and forth between the map and the area/zone selection in the TF.

### Which bus area will you travel in?
![Screenshot 2021-10-05 at 15 16 01](https://user-images.githubusercontent.com/62507489/136040959-b0137e65-8504-46ce-ae04-70bfb01d3b35.png)

### Which train stations will you use?
![Screenshot 2021-10-05 at 15 21 03](https://user-images.githubusercontent.com/62507489/136041834-c02563a3-64cd-42e2-90f1-53bb984cfa37.png)

**Comment by houbly** [comment]
@jkmnch We can't actually do this currently as we have to use session storage to save the users information, which essentially means the info is stored in the tab that the user started their session in. If we open these in a new tab we won't be able to send the user back to where they were in the ticket finder journey

**Comment by KaterinaKir** [comment]
okay but just be aware that this may cause user frustration as we saw in user testing.

**Comment by houbly** [comment]
@KaterinaKir this is what we are currently doing

**Comment by KaterinaKir** [comment]
Ok you can close this issue, just Jake monitor user feedback.
