### ISSUE TITLE
Price difference for 1 day adult metro £6.20- £6.00, which changes again when you select it- to £6.30

### ISSUE THREAD

**Issue by Dunn-R** [wmcadigital/wmn-find-a-ticket#103]
![image](https://user-images.githubusercontent.com/92024188/136203734-5dce1286-e361-4c20-a05a-fa006b1ecfda.png)

**Comment by Dunn-R** [comment]
1 week adults differ too-
![image](https://user-images.githubusercontent.com/92024188/136205816-34d48742-cbe5-468e-9460-76ec31e5b40b.png)

**Comment by Dunn-R** [comment]
Strangely when you select 1 wk or 4 wk Metro from the incorrectly priced menus, they are correct on next page.
Same for d/d's too.
52 week price is correct 👍

**Comment by Dunn-R** [comment]
Adult 1 day peak now- £6.30, o/p £4.80 which i think are the non swift discounted prices. CX please confirm
1 week Adult Metro @£23.00 now good
Both 4 week prices now match
Child issues look fixed - 1 day are now  and £4.60 +£3.50 (non swift price?). Other durations all match.
Student prices match, as do Group/Family days 👍

**Comment by houbly** [comment]
Great I will close this issue.
