### ISSUE TITLE
Unable to select a bus+tram/any bus (yes)/adult/West Midlands/Peak - 

### ISSUE THREAD

**Issue by Dunn-R** [wmcadigital/wmn-find-a-ticket#105]
![image](https://user-images.githubusercontent.com/92024188/136214159-461ea224-f0df-4f1b-bf3e-70879d8cb185.png)
Screen renders blank as above, and annoyingly you can't use back button. I believe the £6.80 1 day bus/metro is missing

**Comment by houbly** [comment]
@Dunn-R this should be fixed now

**Comment by Dunn-R** [comment]
1 day peak £6.80 now there.
re - Screen renders blank - now fixed
