### ISSUE TITLE
Missing 2 week Network 1-5 Off Peak (do we care? or is it no longer available?)

### ISSUE THREAD

**Issue by Dunn-R** [wmcadigital/wmn-find-a-ticket#107]
![image](https://user-images.githubusercontent.com/92024188/136219276-212423c3-193f-4b58-820a-8eca589c129e.png)

**Comment by emilygriffiss** [comment]
This ticket is still available and should be showing please

**Comment by houbly** [comment]
@Dunn-R @emilygriffiss I've found the issue here. It's due to the filter logic for time period 3 which is 15:30 and 18:00. Do you have a list of ticket types that can't be used for time period 3? Just so I can ensure the filter is set up properly

**Comment by emilygriffiss** [comment]
some of the 2 week tickets have been decommissioned recently - but this should be in the data as they will be deactivated. I will just try and grab that time slot data for you!

**Comment by houbly** [comment]
This issue should be fixed now
