### ISSUE TITLE
Travel on any bus: Remove West Midlands Network reference

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-find-a-ticket#116]
When selecting Bus, the content references West Midlands Network which is an old brand name.

Suggest this is changed to "Travel on any bus company in the West Midlands"

<img width="1067" alt="Screenshot 2021-10-11 at 13 23 30" src="https://user-images.githubusercontent.com/66072673/136791840-f86ee51e-7436-45b5-a4f8-5eb7be10e6e5.png">

**Comment by sudheer-rk** [comment]
fixed
