### ISSUE TITLE
Links opening in same window rather than another

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmn-find-a-ticket#181]
Links within the service open within the same window as the form, thereby taking the user out of the flow. For example, the links to locate stations or rail zones in the attached

Text will need amending throughout to indicate the link will open in another window. 

![Screenshot 2022-09-09 at 13 41 21](https://user-images.githubusercontent.com/68856858/189352232-22ee9bb3-a10e-402e-ac07-3810bdfadf42.png)
![Screenshot 2022-09-09 at 13 48 34](https://user-images.githubusercontent.com/68856858/189353471-e95ee881-2609-4559-b7b4-e251ee08fc34.png)

**Comment by sam-wmca** [comment]
This ticket can be closed, as the services that open on these links direct users back into the journey once they've chosen an operator.
