### ISSUE TITLE
User flow being disrupted when looking at rail zone maps

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmn-find-a-ticket#182]
When a user clicks on the 'view rail zones on a map' (or list view), they are taken to the relevant service within the same window, with the from and to fields populated with any previously supplied station names.

At this point, you can then either click back to ticket finder or the Continue CTA, however, both take you to legacy ticket finder service (https://legacy.wmnetwork.co.uk/tickets/?selectedStation0=BHM&selectedStation1=YRD#/) rather than return the user to the find a ticket service.

It's also an issue on the tram user journey when using the view tram zone links.

![Screenshot 2022-09-09 at 13 48 34](https://user-images.githubusercontent.com/68856858/189354938-d300da8b-80be-4ddb-919b-75f95d357cd0.png)
![Screenshot 2022-09-09 at 13 57 16](https://user-images.githubusercontent.com/68856858/189355131-c0cee728-d0e6-4098-ae1a-33c263eb039c.png)

**Comment by sam-wmca** [comment]
This ticket can be closed, as those services will direct users back into the journey once they've chosen a rail/tram zone.
