### ISSUE TITLE
nBus icon missing

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmn-find-a-ticket#186]
There are instances where the hexagonal 'n' icon is missing from the nBus name in the right hand column and is just presented as a standard 'nBus'.

Seems to be an issue after a user selects no to the question of whether they want to travel on any bus. Where as if they select yes, it's the icon version. 

![Screenshot 2022-09-12 at 16 16 45](https://user-images.githubusercontent.com/68856858/189691866-2b65923d-76f0-453f-b549-22416ec011d4.png)
![Screenshot 2022-09-12 at 16 17 02](https://user-images.githubusercontent.com/68856858/189691877-d949c63a-98bc-4049-a55b-7a83164866b2.png)

**Comment by sam-wmca** [comment]
This happens if you select bus > no to any bus in the West Midlands > select a bus company > select 'continue with an nBus ticket'

**Comment by sudheer-rk** [comment]
Some of the bus company names were empty on the ticketInfo object so it was displaying simply as Bus.
