### ISSUE TITLE
Rail zone selection

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-find-a-ticket#99]
When user selects rail zones using a map or list view and clicks 'continue' TK should take them to the next question. At the moment it asks again to confirm rail zones. We did user testing here and majority of users said they don't want to be asked again. 

<img width="1177" alt="Screenshot 2021-10-05 at 14 59 29" src="https://user-images.githubusercontent.com/57525718/136038201-c2dba25f-d9e8-472f-bce1-1e3db7f19357.png">

<img width="1163" alt="Screenshot 2021-10-05 at 14 59 37" src="https://user-images.githubusercontent.com/57525718/136038230-79aa79e9-e32e-4463-84e7-74cfd9668a1d.png">

**Comment by KaterinaKir** [comment]
We tested this with users and they were surprised that we ask them to select stations again. I believe the idea was to tweak rail zone maps service for TK so user can select their stations there.

**Comment by houbly** [comment]
when they return back to the TK journey the stations are prefilled based on what user chose in the find-rail-zones journey so they wouldn't have to enter them twice

**Comment by KaterinaKir** [comment]
ok let's close this issue.
